### ISSUE TITLE
Report/output on the rules applied to build

### ISSUE THREAD

**Issue by jmcgarr** [nebula-plugins/gradle-resolution-rules-plugin#4]
Make sure that the user has a report produced in the /build directory of the changes applies and the output notifies the user that a report is available.

**Comment by DanielThomas** [comment]
Unfortunately we can't tell if all of the rule types are applied, because we're using built in Gradle functionality that doesn't give us the opportunity to tell that the rule logic was applied. 

Align, substitute, reject and deny are possible though, and Gradle logs module replacements, so I think we can provide some solid reporting.
