### ISSUE TITLE
Introduce Configuration with identical names causes problems with other build logic.

### ISSUE THREAD

**Issue by breskeby** [nebula-plugins/gradle-resolution-rules-plugin#61]
Gradle prevents configurations with the same name for a same project / configuration container. This plugin uses reflection to bypass that. This causes different problems within gradle builds 

- with build logic relying on unique configuration names:

```
configurations.all { c -> tasks.create("resolve${c.name}")}
``` 

- using gradle build scans

**Comment by DanielThomas** [comment]
@breskeby yep, all of this configuration hackery is a necessary evil to alignment to work. There's no other way for us to have a copy of a configuration resolve exactly the same way of the source, when we have plugins like dependency lock etc. applying resolution rules by configuration name. 

We never add these to the configuration container, but the add handlers do get called which is why you can see some side effects. The hoops we have to jump through to do something as simple as alignment in a plug-in is why out current OSP contract is focused on replacing these capabilities with core features.

**Comment by DanielThomas** [comment]
We can't change this. We have to live with any side-effects until we can express these rules as dependency constraints.
